### PR TITLE
feat: Default to encrypted storage for Postgres

### PR DESCRIPTION
**Pull request by mogul**
Name a reason this should be otherwise, I dare you! ;)

### CODE REVIEW

**Comment by omerbensaadon** [comment]
@erniebilling can I merge this??

**Comment by erniebilling** [comment]
The plan descriptions now conflict with the default, we should discuss how to clean this up.

**Comment by omerbensaadon** [comment]
@winnab

**Comment by blgm** [comment]
I completely agree that a secure default is preferred. Currently there are some issues around managing updates on "day 2". If a plan default is changed, the next time a service is updated (via cf update-service) then the new default is applied. At best this side-effect could be confusing, but in some situations it can cause Terraform to re-create the resource.

We definitely want to move to a situation where this is the default, but we don't want to do that yet until we have more protection around changing plan defaults.

**Comment by pivotal-marcela-campo** [comment]
We'll be reviewing aws-postgres brokerpak in the near feature and we'll definitely aim to provide secure defaults. So we will most probably make this change as well.

**Review by jhvhs — APPROVED** [review]
LGTM

**Comment by FelisiaM** [comment]
Hi @mogul 

We, unfortunately, had to revert this PR. As per Georges's comment above this change would introduce changes for existing customers that had encryption disabled to enable it immediately as a side effect of any update/upgrade. 

We want to find a better solution to how we can change defaults in the future, but it's not possible right now.

Thanks,
Felisia

**Comment by mogul** [comment]
I understand. We aren't using this broker in production so reverting doesn't affect us.

**Pull request merged**
